# .travis.yml for nina-fw
# adapted from https://github.com/igrr/esp32-cam-demo/blob/master/.travis.yml
sudo: false
language: bash
os:
  - linux

addons:
  apt:
    packages:
      - python3.5
      - gperf

before_install:
  # Save path to the git respository
  - PROJECT_PATH=$(pwd)

install:
  - mkdir -p ~/esp
  - cd ~/esp
  # Get ESP-IDF release/v4.4
  - git clone --branch release/v4.4 --recursive https://github.com/espressif/esp-idf.git
  # Set up IDF
  - cd esp-idf
  - ./install.sh esp32
  - . ./export.sh

script:
  - cd $PROJECT_PATH
  - idf.py build
  - python combine.py

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: "NINA_W102-*.bin"
  skip_cleanup: true
  on:
    tags: true
